version: '3'

networks:
  backend-dev:
    external: true

services:
  php-worker:
    build:
      context: docker/php-worker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/php-worker/supervisor/conf.d:/etc/supervisor/conf.d
      - ./docker/php-worker/supervisor/supervisor.conf:/etc/supervisor/supervisor.conf
      - ./storage/logs/supervisor:/var/log/supervisor
    networks:
      - backend-dev
    environment:
      PHP_IDE_CONFIG: serverName=Docker

  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - backend-dev
    environment:
      PHP_IDE_CONFIG: serverName=Docker

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./docker/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./docker/mysql/dump:/home/root/dump
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
    networks:
      - backend-dev
    cap_add:
        - SYS_NICE

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend-dev
    depends_on:
      - php-fpm

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./docker/redis/cache:/data
    networks:
      - backend-dev